### PR TITLE
Enabled it for 5.7

### PR DESCRIPTION
**Pull request by OwenMelbz**

### CODE REVIEW

**Comment by tabacitu** [comment]
Uuu... totally, nice :-) Have you installed it on 5.7 yourself - works without any changes on our end?

**Comment by AegirLeet** [comment]
5.7 has been released.

[Release Notes](https://laravel.com/docs/5.7/releases#laravel-5.7), [Upgrade Guide](https://laravel.com/docs/5.7/upgrade#upgrade-5.7.0)

**Comment by tabacitu** [comment]
Merged, thank you @OwenMelbz and @AegirLeet !

Just followed the upgrade guide and did all necessary changes to both Base and CRUD - works great. Please let me know if you encounter any issues on L5.7.

Cheers!

**Comment by deepakSP** [comment]
still getting error on 5.7

 backpack/base 0.9.7 requires laravel/framework 5.5.*|5.6.* -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.7.1].

**Comment by OwenMelbz** [comment]
@deepakSP You’ll need to update all of the backpack packages to the latest versions on packagist. The one you’re installing is old

**Comment by deepakSP** [comment]
I am getting this error on fresh Laravel install

**Comment by deepakSP** [comment]
Though I just found out composer is not picking new version.. don't what to do. I guess have to wait.

**Comment by OwenMelbz** [comment]
Waiting won’t solve it 😂 you need to increase the version manually if it’s locked to an old one, the do a composer update

**Comment by deepakSP** [comment]
Tried composer crud 3.4.33

But it say could not find package with 3.4.33 version

**Comment by OwenMelbz** [comment]
The error you got said `backpack/base 0.9.7` not `backpack/crud` - maybe you're changing the wrong package

**Comment by deepakSP** [comment]
Actually I am installing backpack crud which has base dependency. Author has upgraded both package to new version to get Laravel 5.7 working.

Crud to 3.4.33
Base to 0.9.8

But when I am trying to install on fresh Laravel 5.7 I was getting that error as composer not picking new version which allows base and crud to install on 5.7

Tried clearing composer cache but had no luck.

**Comment by OwenMelbz** [comment]
Maybe try just adding both of them to your composer.json e.g

```
"backpack/crud": "^3.4.33",
"backpack/base": "^0.9.8",
```

then a `composer update` just to see what happens?

**Comment by deepakSP** [comment]
Thanks for helping.

Manually adding worked !
"backpack/crud": "3.4.*"

**Pull request merged**
