### PR TITLE
add topbar_content.blade.php to menu.blade.php

### PR DESCRIPTION
**Pull request by tswonke**
Now we can add items to the top menu as easy as to the sidebar.

I don't think that this file has to be published because I assume that this is not often used. But with this pull request we can just create a `topbar_content.blade.php` in our project and add items without overwriting `menu.blade.php`

### CODE REVIEW

**Comment by lloy0076** [comment]
It probably should be published with the other asset (sidebar) for consistency.

**Comment by lloy0076** [comment]
And should it be optional via configuration:

1. Should it appear _at all_?
2. When should it appear?

...and so forth.

At the moment it looks as though this proposal believes it should appear when the _default_ guard responds "yes".

**Comment by tswonke** [comment]
@lloy0076 
I understand your questions and one can think of diverse possible optimizations/configurations.
This was intended to be a very quick not-breaking change for a function that is probably not used very often.

btw: the used check (default guard) is the same as in `sidebar.blade.php`, or do I miss something?

**Comment by AbbyJanke** [comment]
Everything looks good to me, saw you fixed the spelling 👍 I say its good to go, but i'm curious if we should add this to the "minimal" views that get published when running `backpack:base:install`.

**Comment by tswonke** [comment]
Thank you @AbbyJanke !
I'm not sure about whether this should be published by default, what do you think @tabacitu ?

**Comment by tswonke** [comment]
any change to get this merged @tabacitu ? :-)
what do you think about publishing by default?

**Comment by tswonke** [comment]
Sorry, I will open another pull-request. I deleted this repo after being added to the team.

**Comment by tswonke** [comment]
see #302

**Pull request closed without merging**
