### PR TITLE
[Merged] BackpackUser model picks up its parent's relationships

### PR DESCRIPTION
**Pull request by tabacitu**
By default, we use BackpackUser model everywhere, and ```BackpackUser extends User```. But the way Eloquent works, that extension DOES NOT include relationships. So when you have Roles, Permissions or other relationships on the User model, the BackpackUser object WILL NOT have those relationships.

This makes it more difficult to use packages like PermissionManager (see issues https://github.com/Laravel-Backpack/PermissionManager/issues/169, https://github.com/Laravel-Backpack/PermissionManager/issues/166), but also with home-grown relationships. You'd expect if you add a relationship to the User model, that BackpackUser would also pick it up. Right now it DOES NOT. And the helper we recommend using for getting the current user, ```backpack_user()```, returns a BackpackUser model by default.

Apparently forcing Eloquent to pick up its parent's relationships isn't that easy, but there's [a package by Tighten that does the job](https://github.com/tightenco/parental). They say it's alpha, but in my experience it works really well.

### CODE REVIEW

**Comment by tabacitu** [comment]
**Note:** this package does not support Laravel 5.5.

So it can only be merged in a bumped version of Backpack\Base, where we drop support for Laravel 5.5 - which was due anyway.

**Comment by tabacitu** [comment]
Merged into the ```dev``` branch. Will be closed automatically when https://github.com/Laravel-Backpack/Base/pull/324 gets merged.

**Comment by tabacitu** [comment]
Closing - merged into ```dev```. Will be launched later this week.

**Comment by mpixelz** [comment]
looking forward for this..

i just started playing with different guards for admin and users.. but now cant use @can() functions in the admin section.. as they gets ignored altogether.

**Comment by tabacitu** [comment]
Yes - tha plan is to launch today or tomorrow 🤞 That’s what I said last week too, but I kept cramming more and more features and bug fixes into this update - it’s going to be a big one 😄

**Pull request closed without merging**
