### PR TITLE
Make the admin routes serializable

### PR DESCRIPTION
**Pull request by SabatinoMasala**
Removed the closure-based redirect, so the routes can be cached (serialized) with `php artisan route:cache`.

### CODE REVIEW

**Comment by tabacitu** [comment]
Thank you! :-)

**Comment by SabatinoMasala** [comment]
Thanks for merging! Quick question though, why does StyleCI keep failing, while PHP Code Sniffer gives me no errors / warnings on AdminController.php (using PSR-2)?

**Comment by tabacitu** [comment]
I think StyleCI is pickier than PHP Code Sniffer. This time, for example, it didn't like that [a comment of yours did not have a trailing dot](https://github.com/Laravel-Backpack/Base/commit/6b6205b9557316991616de57ef9292b711058315) :-)  

It's set to autocorrect, so after any merge StyleCI will do its thing. Not even worth looking if StyleCI approves before merging, really.

**Comment by SabatinoMasala** [comment]
Ah I see! Thanks for elaborating! :)

**Pull request merged**
