### PR TITLE
add sitemap.xml generator

### PR DESCRIPTION
**Pull request by averuga**
Hi, friends! Thank you so much for your product. Please add sitemap.xml generator  with the possibility of excluding private materials. This is important for SEO. Get comfortable finished product. Thanks in advance. Sincerely, Dmitry Averin

### CODE REVIEW

**Comment by OwenMelbz** [comment]
@averuga Hi,

Although I see that some users will use this - I don't think its what backpack is designed for.

Backpack is an extendable admin interface, with baked in CRUD system.

It has no concept of your frontend, this is up to you to build as you like.

That includes a sitemap, for example we have several applications that use backpack that do not even need sitemaps as they power APIs.

Although it might be useful, I feel its outside of the remit of Backpack - there are plenty of open source projects dedicated to sitemaps which you can see here https://www.google.co.uk/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=laravel%20sitemap%20generator&oq=laravel%20sitemap%20generator&aqs=chrome.0.0j69i57j69i60l2.2959j0j7

**Comment by averuga** [comment]
@OwenMelbz 
Thank you for your decision. It will be very convenient for standard web sites. Especially for beginners, like me. Turn-key solution.

**Comment by tabacitu** [comment]
Hi @averuga ,

This PR seems to merge ```master``` into the ```laravel-5.4``` branch, which is fine with me, I'll merge it.

About the sitemap.xml generator - I think it might be useful in [Backpack\PageManager](https://github.com/Laravel-Backpack/PageManager). But let's continue the conversation about it there.

Cheers!

**Comment by averuga** [comment]
@tabacitu
Hi! Thank you. I think this will be very useful not only for static pages, but also for materials, published in blog format - news, recipes, etc. For all materials that need to be indexed by search engines and ranked in the search results.

**Pull request merged**
