### PR TITLE
Allow clear in control select2 from ajax

### PR DESCRIPTION
**Pull request by eduardoarandah**
Related to 
https://github.com/Laravel-Backpack/CRUD/compare/master...eduardoarandah:patch-1

### CODE REVIEW

**Comment by lloy0076** [comment]
Errr, what's this? Is this something that should have gone through with the thing related?

**Comment by eduardoarandah** [comment]
Yes. Without this styling, all you see is a very small "x" 

In wide screens, it goes too far on the right side. 

This style makes it look like the screenshots you already saw. 

This is a separate PR because the stylesheet is in this repo

**Comment by eduardoarandah** [comment]
before and after on a 1980x1080 monitor

before

after

**Comment by tabacitu** [comment]
Love this! Thank you! I was skeptical about including it in Base and not the field itself but you're right, it's general.

**Comment by tabacitu** [comment]
@eduardoarandah mind shooting me an email at hello@tabacitu.ro ? I have something to discuss in private and can't find your email.

**Pull request merged**
