### PR TITLE
[4.0][Feature][Ready] Widgets (aka cards, charts)

### PR DESCRIPTION
**Pull request by tabacitu**
This adds the ability to add _widgets_ from the controller. Widgets are content blocks that can look&work in _any freaking way_ :-). Their syntax is similar to CRUD fields/columns/filters/etc, because _at their core_ they're just blade views.

Widgets can be useful to add:
- charts
- notices
- extra content

# Widget sections

The default ```layout``` has two **widget sections** where you can push cards:
- ```before_content```
- ```after_content```

For example, this is how you can add content in the Dashboard, before and after the main hero unit:
```php
/**
     * Show the admin dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard()
    {
        $this->data['title'] = trans('backpack::base.dashboard'); // set the page title
        $this->data['widgets']['before_content'] = [
            [
                'type' => 'card',
                'wrapperClass' => 'col-sm-6 col-md-4',
                'content' => [
                    'header' => 'Some card title',
                    'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non mi nec orci euismod venenatis. Integer quis sapien et diam facilisis facilisis ultricies quis justo. Phasellus sem <b>turpis</b>, ornare quis aliquet ut, volutpat et lectus. Aliquam a egestas elit. <i>Nulla posuere</i>, sem et porttitor mollis, massa nibh sagittis nibh, id porttitor nibh turpis sed arcu.',
                ]
            ],
        ];
        $this->data['widgets']['after_content'] = [
            [
                'type' => 'card',
                'wrapperClass' => 'col-sm-6 col-md-4',
                'class' => 'card text-white bg-primary text-center',
                'content' => [
                    // 'header' => 'Another card title',
                    'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non mi nec orci euismod venenatis. Integer quis sapien et diam facilisis facilisis ultricies quis justo. Phasellus sem <b>turpis</b>, ornare quis aliquet ut, volutpat et lectus. Aliquam a egestas elit.',
                ]
            ],
        ];

        return view('backpack::dashboard', $this->data);
    }
```

Result:

Screenshot 2019-07-30 at 18 41 53

However, this is a pretty simple view. I expect all views to have the ```before_content``` and ```after_content``` widget sections, but more complex views could have more widget sections. For example:
- all CRUD views could have ```before_heading```, ```after_heading```;
- CRUD's List view could also have ```before_filters```, ```after_filters```, ```before_table```, ```after_table```;
- etc

Of course, you can also push widgets into those sections from the view. For example, your ```dashboard.blade.php``` could look like this:

```php
@extends('backpack::layouts.top_left')

@php
$widgets['before_content'][] = [
        'type'        => 'jumbotron',
        'heading'     => trans('backpack::base.welcome'),
        'content'     => trans('backpack::base.use_sidebar'),
        'button_link' => backpack_url('logout'),
        'button_text' => @Laravel-Backpack/community-members backpack::base.logout'),
    ];
@endphp

@section('content')
@endsection
```
_Arguably_, this is an even better way of using widgets - since the presentation logic will be contained within the views, and the views alone.

# How to create or overwrite a default widget

Similar to CRUD fields:
- you can add new widgets by creating a file inside ```resources/views/vendor/backpack/base/widgets```;
- you can overwrite default widgets by creating a file inside ```resources/views/vendor/backpack/base/widgets```;
- JS and CSS can be used in the blade file by pushing to the existing stacks (```before_styles```, ```after_styles```, ```before_scripts```, ```after_scripts```);
- you can use widgets from a different directory or package, by mentioning a different ```viewNamespace```, for example:
```diff
        $this->data['widgets']['after_content'] = [
            [
                'type' => 'card',
+               'viewNamespace' => 'package::widgets',
                'wrapperClass' => 'col-sm-6 col-md-4',
                'class' => 'card text-white bg-primary text-center',

                'content' => [
                    // 'header' => 'Another card title',
                    'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis non mi nec orci euismod venenatis. Integer quis sapien et diam facilisis facilisis ultricies quis justo. Phasellus sem <b>turpis</b>, ornare quis aliquet ut, volutpat et lectus. Aliquam a egestas elit.',
                ]
            ],
        ];
```

# Widget types

In this first draft, there's only one widget, ```card```. It outputs a simple Bootstrap card with a heading. You can change how it looks by manipulating class names - both widgets in the screenshot above are using the ```card``` widget.

Of course, more default widgets are needed for this feature to be useful. Hopefully, Backpack developers will be also create custom widgets, and share them with the community. **Here's what I believe would be some useful widgets - let me know what you think**.

## MUST
- [x] [small_number](https://backstrap.net/widgets.html)
- [ ] [small_pie_chart](https://backstrap.net/widgets.html)
- [ ] [small_line_chart](https://backstrap.net/widgets.html)
- [ ] [small_bar_chart](https://backstrap.net/widgets.html)
- [x] [card](https://backstrap.net/base/cards.html)
- [x] [alert](https://backstrap.net/notifications/alerts.html)

## SHOULD
- [ ] [line_chart](https://backstrap.net/charts.html)
- [ ] [bar_chart](https://backstrap.net/charts.html)
- [ ] [pie_chart](https://backstrap.net/charts.html)
- [ ] [doughnot_chart](https://backstrap.net/charts.html)
- [ ] [radar_chart](https://backstrap.net/charts.html)
- [ ] [polar_area_chart](https://backstrap.net/charts.html)

## COULD
- [ ] [carousel](https://backstrap.net/base/carousel.html)
- [ ] [accordion](https://backstrap.net/base/collapse.html) (aka collapse)
- [x] div (to group one or more widgets into a div) 
- [x] [jumbotron](https://backstrap.net/base/jumbotron.html)
- [ ] [tabs](https://backstrap.net/base/tabs.html)
- [ ] [progress_bar](https://backstrap.net/base/progress.html)
- [ ] [breadcrumb](https://backstrap.net/base/breadcrumb.html)

## WON'T
... idk ...

# Feedback needed

Feedback anyone? Is ```widgets``` a good name? Previously I called it "cards" but it felt odd that "cards" was the name of the feature, but also one of the "cards". Confusing. Sounded to me like "widgets" is a better name, because it's more broad, but I never particularly liked this word - makes it sound generic.

Do you mind that it doesn't have a Facade, that you add the widgets by creating simple arrays that get passed to the view? Or does this just make it easy to understand how it works? If it were to have a Facade or helper, what would it be? ```Widget::section('before_content')->add($widgetDefinitionArray)```?

### CODE REVIEW

**Comment by tabacitu** [comment]
Merged into the ```v4``` branch. Let's keep this branch alive until we push all must-have widgets.

**Comment by tabacitu** [comment]
More example usage - for the docs:

```php
        $this->data['widgets']['before_content'][] = [
            'type'        => 'jumbotron',
            'heading'     => trans('backpack::base.welcome'),
            'content'     => trans('backpack::base.use_sidebar'),
            'button_link' => backpack_url('logout'),
            'button_text' => trans('backpack::base.logout'),
        ];
        $this->data['widgets']['before_content'][] = [
            'type'        => 'alert',
            'class'       => 'alert alert-success mb-2',
            'heading'     => trans('backpack::base.welcome'),
            'content'     => trans('backpack::base.use_sidebar'),
            'close_button' => true,
        ];
```

**Comment by tabacitu** [comment]
```progress``` and ```progress_white``` widgets:

Screenshot 2019-08-05 at 12 48 23



```php
        $this->data['widgets']['before_content'][] = [ 'type' => 'div', 'class' => 'row', 'content' => [
            [
                'type'        => 'progress',
                'class'       => 'card text-white bg-primary mb-2',
                'value'       => '11.456',
                'description' => 'Registered users.',
                'progress'    => 57, // integer
                'hint'        => '8544 more until next milestone.',
            ],
            [
                'type'        => 'progress',
                'class'       => 'card text-white bg-warning mb-2',
                'value'       => '89.9%',
                'description' => 'Of quota achieved.',
                'progress'    => 89, // integer
                'hint'        => 'Sold 671 products this month.',
            ],
            [
                'type'        => 'progress',
                'class'       => 'card text-white bg-success mb-2',
                'value'       => '$237',
                'description' => 'Average sale price.',
                'progress'    => 75, // integer
                'hint'        => 'Out of 671 sales.',
            ],
            [
                'type'        => 'progress',
                'class'       => 'card text-white bg-danger mb-2',
                'value'       => '8.7%',
                'description' => 'Churn.',
                'progress'    => 9, // integer
                'hint'        => '1000 users stopped paying so far.',
            ],
        ]];
        $this->data['widgets']['before_content'][] = [ 'type' => 'div', 'class' => 'row', 'content' => [
            [
                'type'        => 'progress_white',
                'class'       => 'card mb-2',
                'value'       => '11.456',
                'description' => 'Registered users.',
                'progress'    => 57, // integer
                'progressClass' => 'progress-bar bg-primary',
                'hint'        => '8544 more until next milestone.',
            ],
            [
                'type'        => 'progress_white',
                'class'       => 'card mb-2',
                'value'       => '89.9%',
                'description' => 'Of quota achieved.',
                'progress'    => 89, // integer
                'progressClass' => 'progress-bar bg-warning',
                'hint'        => 'Sold 671 products this month.',
            ],
            [
                'type'        => 'progress_white',
                'class'       => 'card mb-2',
                'value'       => '$237',
                'description' => 'Average sale price.',
                'progress'    => 75, // integer
                'progressClass' => 'progress-bar bg-success',
                'hint'        => 'Out of 671 sales.',
            ],
            [
                'type'        => 'progress_white',
                'class'       => 'card mb-2',
                'value'       => '8.7%',
                'description' => 'Churn.',
                'progress'    => 9, // integer
                'progressClass' => 'progress-bar bg-danger',
                'hint'        => '1000 users stopped paying so far.',
            ],
        ]];
```

**Comment by tabacitu** [comment]
Note - I think this is ready for prime-time. Other than adding more widgets, there's not much more we can do. Maybe add a few more widget sections to the layout, but that's it...

**Comment by tabacitu** [comment]
Merged into v4. Added to the docs. New widgets still need to be added.

**Comment by FreddyCrugger** [comment]
Are the charts added to the widgets please? As I cannot see them in the doc. Thanks.

**Comment by FreddyCrugger** [comment]
Thanks Tabacitu

**Pull request merged**
